home/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.TaskListView.as_view(), name='all'),
    path('register/', views.register_view, name='register'),
    path('task/<int:pk>', views.TaskDetailView.as_view(), name='task_detail'),
    path('task/create', views.TaskCreateView.as_view(success_url=reverse_lazy('home:all')), name='task_create'),
    path('task/<int:pk>/update', views.TaskUpdateView.as_view(success_url=reverse_lazy('home:all')), name='task_update'),
    path('task/<int:pk>/delete', views.TaskDeleteView.as_view(success_url=reverse_lazy('home:all')), name='task_delete'),
]

taskManager/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('home.urls')),
]

home/models.py
from django.db import models
from django.conf import settings


class Task(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField(null=True, blank=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'description']


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

home/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from .forms import TaskForm, CreateUserForm
from .models import Task
from .owner import OwnerListView, OwnerDetailView, OwnerUpdateView, OwnerDeleteView, OwnerCreateView


# register views

def register_view(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("login")
    ctx = {'form': form}
    return render(request, "registration/register.html", ctx)

# tasks crud views


class TaskListView(OwnerListView):
    model = Task
    # template is home/task_list.html

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Retrieve all tasks
        tasks = Task.objects.filter(owner=self.request.user).order_by('-updated_at')

        # Paginate tasks
        paginator = Paginator(tasks, 3)  # Show 3 tasks per page

        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        form = TaskForm()
        context['create_form'] = form
        context['page_obj'] = page_obj
        return context


class TaskDetailView(OwnerDetailView):
    model = Task
    # template is home/task_detail.html


class TaskCreateView(OwnerCreateView):
    model = Task
    template_name = 'home/task_list.html'
    fields = ['name', 'description']

    # """Overriding get_context_data to change name of creating form to create_form"""
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['create_form'] = context['form']
    #     del context['form']
    #     return context


class TaskUpdateView(OwnerUpdateView):
    model = Task
    fields = ['name', 'description']
    template_name = 'home/task_list.html'

    """Overriding get_context_data to change name of updating form to update_form"""
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tasks = Task.objects.filter(owner=self.request.user).order_by('-updated_at')

        # Paginate tasks
        paginator = Paginator(tasks, 3)  # Show 3 tasks per page

        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        form = TaskForm()
        context['create_form'] = form
        context['page_obj'] = page_obj
        context['update_form'] = context['form']
        del context['form']
        return context


class TaskDeleteView(OwnerDeleteView):
    model = Task
    # template is home/task_confirm_delete.html

templates/base.html
{% load humanize %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Task Manager{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css" rel="stylesheet">
<!-- Latest compiled and minified CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">

<!-- Latest compiled JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body class="bg-light">
{#<div class="container d-grid justify-content-md-center">#}
    {% block content %}
    {% endblock %}
    
{#</div>#}

</body>
</html>

templates/home/create_form.html
{#{% extends "base.html" %}#}
{#{% block content %}#}
{#<p>#}
{#  <form action="" method="post">#}
{#    {% csrf_token %}#}
{#    {{ form.as_p }}#}
{#    <input type="submit" value="Submit">#}
{#    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'home:all' %}';return false;">#}
{#  </form>#}
{#</p>#}
{#{% endblock %}#}

{% load humanize %}
{% load static %}

templates/home/task.html
{% load humanize %}
{% load static %}

<div class="card-header">
  <small class="text-muted">Last updated: {{ task.updated_at|naturaltime }}</small>
</div>
<div class="card-body">
  <div class="card-title">
      <h4>{{ task.name }}</h4>
  </div>
  <div class="card-text text-muted">{{ task.description }}</div> <br>
  <a class="card-link text-muted" href="{% url 'home:task_update' task.id %}">Edit</a>
  <a class="card-link text-muted" href="{% url 'home:task_delete' task.id %}">Delete</a>
</div>

templates/home/task_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<h1>Delete Task</h1>

<p>Are you sure you want to delete task: {{ task.name }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

templates/home/task_detail.html
{% extends "base.html" %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/4.2/ref/contrib/humanize -->
{% block content %}
<p>Updated: {{ task.updated_at|naturaltime }}</p>
<h2>{{ task.name }}</h2>
<p>{{ task.description }}</p>
<a href="{% url 'home:task_update' task.id %}">Update</a>
<a href="{% url 'home:task_delete' task.id %}">Delete</a>
<p><a href="{% url 'home:all' %}">Back to all tasks</a></p>
{% endblock %}

templates/home/task_list.html
{% extends "base.html" %}
{% load humanize %}
{% load static %}

{% block content %}
{#<div class="row align-items-center justify-content-center mb-3">#}
{#    <div class="col-auto"><h1 class="m-4">{{ user.username }}'s tasks</h1></div>#}
{#    <form class="col-auto" action="{% url 'logout' %}" method="post">#}
{#        {% csrf_token %}#}
{#        <button class="btn btn-danger m-3" type="submit">Logout</button>#}
{#        <input type="hidden" name="next" value="{% url "login" %}" />#}
{#    </form>#}
{#</div>#}
    <nav class="navbar navbar-expand-lg navbar-light bg-light m-2">
        <div class="container-fluid">
            
            <div class="navbar-brand">{{ user.username }}'s tasks</div>
    
    <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">
            <i class="bi bi-person"></i>
        </button>
        <div class="dropdown-menu  dropdown-menu-end" aria-labelledby="dropdownMenuButton">
{#            <p class="dropdown-item-text">@{{ user.username }}</p>#}
            <hr class="dropdown-divider">
            <form action="{% url 'logout' %}" method="post" class="dropdown-item-text">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Logout</button>
                <input type="hidden" name="next" value="{% url "login" %}" />
            </form>
        </div>
            
    </div>
    </div>

        
    </nav>
    

    
{% if page_obj %}
  {% for task in page_obj %}
      {% if task.id != object.id %}
          <div class="card text-dark m-3" style="max-width: 30rem;">
              {% include 'home/task.html' %}
          </div>
      {% else %}
          <div class="card m-3 border-primary" style="max-width: 30rem;">
          <div class="card-header">
              <small class="text-muted">Last updated: {{ task.updated_at|naturaltime }}</small>
            </div>
            <div class="card-body">
                <form action="{% url 'home:task_update' task.id %}" method="post">
                {% csrf_token %}
                    
                  <div class="card-title">
                      <input class="form-control" type="text" id="creating_name" name="name" value="{{ task.name }}" required/>
                  </div>
                  <div class="card-text text-muted mb-2">
                      <textarea class="form-control form-control-sm" type="text" id="creating_description" name="description">{{ task.description }}</textarea>
                  </div>
            
                <input class="btn btn-primary" type="submit" value="Edit task">
                <input class="btn btn-secondary m-2" type="submit" value="Cancel" onclick="window.location.href='{% url 'home:all' %}';return false;">
            
            </form>
                </div>
            </div>
      {% endif %}
      
  {% endfor %}
{#    Pagination#}
    {% if page_obj.has_other_pages %}
        <nav>
        <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1">&laquo;</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link">&laquo;</span>
            </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <li class="page-item active">
                    <span class="page-link">{{ num }}</span>
                </li>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link">&raquo;</span>
            </li>
        {% endif %}
    </ul>
        </nav>
    
    {% endif %}
{% else %}
  <h5>You have no tasks. Create new task.</h5>
{% endif %}
<div class="card border-dark text-black m-3 bg-light" style="max-width: 30rem;">
<div class="card-body">
    <form action="{% url 'home:task_create' %}" method="post">
    {% csrf_token %}

      <div class="card-text">
          <label class="form-label text-muted" for="creating_name"><small>Name</small></label>
          <input class="form-control form-control" type="text" id="creating_name" name="name" required/>
      </div>
      <div class="card-text text-muted mb-2">
          <label class="form-label text-muted" for="creating_description"><small>Description</small></label>
          <textarea class="form-control form-control-sm" type="text" id="creating_description" name="description"></textarea>
      </div>
    <input class="btn btn-primary" type="submit" value="Create new task">
    <input class="btn btn-secondary m-2" type="submit" value="Cancel" onclick="window.location.href='{% url 'home:all' %}';return false;">

    

</form>
    </div>
</div>



{% endblock %}